version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  source_db:
    image: postgres:15
    environment:
      POSTGRES_DB: sourcedb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5433:5432"
    volumes:
      - ./source_db/init.sql:/docker-entrypoint-initdb.d/init.sql

  target_db:
    image: postgres:15
    environment:
      POSTGRES_DB: targetdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5434:5432"
    volumes:
      - ./target_db/init.sql:/docker-entrypoint-initdb.d/init.sql

  producer:
    build: ./producer
    depends_on:
      - source_db
      - kafka
    environment:
      DB_HOST: source_db
      DB_NAME: sourcedb
      DB_USER: user
      DB_PASS: pass
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  consumer:
    build: ./consumer
    depends_on:
      - target_db
      - kafka
    environment:
      DB_HOST: target_db
      DB_NAME: targetdb
      DB_USER: user
      DB_PASS: pass
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
